### ISSUE TITLE
sum of natural numbers need to be updated to be O(1) instead of O(n)

### ISSUE THREAD

**Issue by rudraneel18** [Idhant-6/Hacktoberfest-2022#63]
Please assign me the hacktoberfest or hacktoberfest-accepted tag for the same

**Comment by Idhant-6** [comment]
Hi, Can you please propose the changes if you want? That'd be great... btw, Thank you 🙂🌟

**Comment by siwanijaiswal** [comment]
I have created pull request for the same You may merge it
